### ISSUE TITLE
如果可能，请发布已打包的版本

### ISSUE THREAD

**Issue by lonelysam3** [heipiao233/dmclc#1]
现有版本只有zip和tar.gz版本，但大多数玩家并不会打包，请发布打包后的版本(比如exe)。
同时你可以尝试类似BakaXL的宣传方法来使你的启动器更广为人知。

**Comment by heipiao233** [comment]
不会的。这是一个启动器框架，不是一个能直接使用的启动器。后续会基于此框架开发一款启动器。
